services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "18080:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/mca/Desktop/Internal Test:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home:
